//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Stock
    {
        public string Code { get; set; }
        public decimal ZSZ { get; set; }
        public decimal LTSZ { get; set; }
        public decimal ZGB { get; set; }
        public decimal LTGB { get; set; }
    }
}
